name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 파일 디버깅 (Dockerfile 존재 여부 확인)
    - name: Debug repository files
      run: ls -la

    # 3. Amazon ECR 로그인
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # 4. Docker 이미지 빌드 및 ECR로 푸시
    - name: Build and push Docker image to Amazon ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest