name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Amazon ECR 로그인
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}

    # 3. Docker 이미지 빌드 및 ECR로 푸시
    - name: Build and push Docker image to Amazon ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    # 4. EC2에 SSH 연결 후 배포
    - name: Deploy to EC2
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # AWS ECR 로그인
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

          # 최신 이미지 가져오기
          docker pull $ECR_REGISTRY/$IMAGE_NAME:latest

          # 기존 컨테이너 중지 및 삭제
          docker stop my-container || true
          docker rm my-container || true

          # 새 컨테이너 실행 서버 다운으로 인해 주석 처리
          # docker run -d --name my-container -p 80:80 $ECR_REGISTRY/$IMAGE_NAME:latest
        EOF