name: main branch auto ci process script

on: # 아래 job을 실행시킬 action
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.9 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.EC2_HOST }} # ec2 인스턴스 ip
          username: ${{ secrets.EC2_USER }} # ubuntu 아이디
          key: ${{ secrets.EC2_SSH_KEY }} # ec2 인스턴스 pem key
          script: | # 실행될 스크립트
            cd /phoenix
            git pull
