name: main branch auto ci process script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "Deploying to server..."
            if [ ! -d "/phoenix" ]; then
              echo "Directory /phoenix not found. Creating directory..."
              sudo mkdir -p /phoenix
              sudo chown -R $USER:$USER /phoenix
            fi
            cd /phoenix
            if [ ! -d ".git" ]; then
              echo "Repository not found. Cloning repository..."
              git clone https://github.com/Jackjack5922/phoenix /phoenix
            else
              echo "Repository found. Fetching latest changes..."
              git fetch origin
              git reset --hard origin/main
            fi